# Generated by Django 5.0.4 on 2024-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='cooktime',
            field=models.IntegerField(verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='images',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='ingredients',
            field=models.TextField(verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='recipe',
            field=models.TextField(verbose_name='Рецепт'),
        ),
    ]
